### ISSUE TITLE
HUD element size doesnt scale the HUD Scale setting, rather the current zoom level

### ISSUE THREAD

**Issue by Feathertoes** [SmoothSpatula/SmoothSpatula-DroneHUD#2]
![Risk_of_Rain_Returns_M1j01G8hNg](https://github.com/SmoothSpatula/SmoothSpatula-DroneHUD/assets/70271757/31be47b4-9e5e-4edb-8cae-785c791e7d0b)
![Risk_of_Rain_Returns_JWylVhCoXS](https://github.com/SmoothSpatula/SmoothSpatula-DroneHUD/assets/70271757/1e3f5eac-6b3e-46cb-909d-2754c495c16e)

**Comment by LoveBetween** [comment]
Indeed, fixing this for version 1.0.2
